const eventsData = [
    {
        id: 1,
        category: "main-event",
        title: "Freshers' Orientation",
        date: "2026-08-14",
        image: "photos and videos/ORIENTATION COMMITTEE.jpeg",
        venue: "Around Campus",
        time: "10:00 AM - 4:00 PM",
        leader: "Chairperson - Michael Odhiambo",
        contactName: "Michael Odhiambo",
        contactPhone: "+254 705047204",
        description: "A welcoming event for all new students joining the campus. Get to know the CU leadership, various ministries, and enjoy fun activities and fellowship."
    },
    {
        id: 2,
        category: "fellowship",
        title: "Weekly Bible Study",
        date: "2026-03-15",
        image: "photos and videos/BIBLE STUDY SESSIONS.jpeg",
        venue: "Guided by the BS Pastor",
        time: "5:00 PM - 6:30 PM",
        leader: "Bible Study Coordinator",
        contactName: "Cindy Wangari",
        contactPhone: "+254 787652031",
        description: "Join us for an in-depth study of the book of Romans. Open to all students."
    },
    {
        id: 3,
        category: "retreat",
        title: "Football Retreat",
        date: "2026-02-05",
        image: "photos and videos/UKCCU FOOTBALL PIC 2.jpeg",
        venue: "Vet Lab Field",
        time: "All Day",
        leader: "2nd Vice Chair",
        contactName: "Alan Ng'ang'a",
        contactPhone: "+254 715282350",
        description: "A time of gaming, having fun, and bonding for all CU leaders. Snacks provided."
    },
    {
        id: 4,
        category: "outreach",
        title: "Mission Work",
        date: "2025-10-20",
        image: "photos and videos/MISSION LOOK.jpeg",
        venue: "Kabete Market",
        time: "8:00 AM - 12:00 PM",
        leader: "Outreach Ministry",
        contactName: "Cindy Hazel",
        contactPhone: "+254 733 333333",
        description: "Taking the gospel to the communities around campus and within Kenya"
    },
    {
        id: 5,
        category: "main-event",
        title: "Worship Sunday",
        date: "2026-05-10",
        image: "photos and videos/PRAISE AND WORSHIP.jpeg",
        venue: "844 Hall",
        time: "9:00 PM - 6:00 PM",
        leader: "Worship Coordinator",
        contactName: "Paul Kitonga",
        contactPhone: "+254 715054447",
        description: "A Sunday of high praise and deep worship. Feature guest artist to be announced."
    },
    {
        id: 6,
        category: "fellowship",
        title: "Livingstone - Men's Fellowship",
        date: "2026-02-23",
        image: "photos and videos/LIVINGSTONE UKCCU.JPG",
        venue: "Small Lecture Theater",
        time: "5:00 PM - 6:30 PM",
        leader: "Men's Ministry Leader",
        contactName: "James Njuguna",
        contactPhone: "+254 768517142",
        description: "A gathering for brothers to encourage and sharpen one another."
    },
    {
        id: 7,
        category: "fellowship",
        title: "Rubies - Ladies's Fellowship",
        date: "2026-02-23",
        image: "photos and videos/Exec Ladies.jpeg",
        venue: "School Mess ",
        time: "5:00 PM - 6:30 PM",
        leader: "Ladies's Ministry Leader",
        contactName: "Cindy Hazel",
        contactPhone: "+254 795273360",
        description: "A gathering for ladies to encourage and sharpen one another."
    }
];
