const eventsData = [
    {
        id: 1,
        category: "fellowships",
        title: "JCC Worship and Prayer Night",
        date: "2026-04-03",
        image: "photos and videos/UKCCU IN JCC PIC 1.JPG",
        venue: "Around Campus",
        time: "7:30 PM - 5:00AM",
        leader: "Chairperson - Michael Odhiambo",
        contactName: "Michael Odhiambo",
        contactPhone: "+254 705047204",
        description: "All the CUs in UoN Campuses come together for a night of worship and prayer. We shall all leave by 7:30pm. This Friday 3rd of April."
    },
    {
        id: 2,
        category: "outreach",
        title: "Interversity Street Evangelism",
        date: "2026-04-25",
        image: "photos and videos/Interversity Poster.jpeg",
        venue: "Nairobi CBD Streets",
        time: "4:00 PM - 7:00 PM",
        leader: "Outreach Coordinator",
        contactName: "Denis Ouma",
        contactPhone: "+254 705696558",
        description: "Join us as we take the gospel to the streets of Nairobi. A time of sharing the love of Christ with those around us."
    },
    {
        id: 3,
        category: "bonding",
        title: "Livingstone Bonding Day",
        date: "2026-03-02",
        image: "photos and videos/Livingstone Mbuzi.jpeg",
        venue: "DCUK- Church",
        time: "All Day",
        leader: "2nd Vice Chair",
        contactName: "Alan Ng'ang'a",
        contactPhone: "+254 715282350",
        description: "A time of gaming, having fun, and bonding for all CU men. Meals in plenty."
    },
    {
        id: 4,
        category: "outreach",
        title: "Laikipia Mega Mission",
        date: "2026-05-30",
        image: "photos and videos/Laikipia Mission Poster.jpeg",
        venue: "Laikipia - Kahuruko",
        time: "All 10 days of the mission",
        leader: "Outreach Coordinator",
        contactName: "Denis Ouma",
        contactPhone: "+254 705696558",
        description: "Taking the gospel to the unreached in Laikipia. Join us for a life-changing experience as we serve and share the love of Christ."
    },
    {
        id: 5,
        category: "main-event",
        title: "Worship Sunday",
        date: "2026-05-10",
        image: "photos and videos/PRAISE AND WORSHIP.jpeg",
        venue: "844 Hall",
        time: "9:00 AM - 5:00 PM",
        leader: "Worship Coordinator",
        contactName: "Paul Kitonga",
        contactPhone: "+254 715054447",
        description: "A Sunday of high praise and deep worship. Feature guest artist to be announced."
    },
    {
        id: 6,
        category: "fellowship",
        title: "Livingstone Sunday",
        date: "2026-04-19",
        image: "photos and videos/LIVINGSTONE UKCCU.JPG",
        venue: "844 Hall",
        time: "9:00 AM - 12:00 PM",
        leader: "Men's Ministry Leader",
        contactName: "James Njuguna",
        contactPhone: "+254 768517142",
        description: "A special Sunday for the men to be encouraged and empowered in their walk with Christ as they lead the service."
    },
    {
        id: 7,
        category: "fellowship",
        title: "Rubies Sunday",
        date: "2026-04-12",
        image: "photos and videos/Exec Ladies.jpeg",
        venue: "844 Hall",
        time: "9:00 AM - 12:00 PM",
        leader: "Ladies's Ministry Leader",
        contactName: "Joy Ndanu",
        contactPhone: "+254 796550252",
        description: "A special Sunday for the ladies to be encouraged and empowered in their walk with Christ as they lead the service."
    }
];
